dicionario['pt-geek'] = {
	"(longe|distante) do (pc|computador|notebook|note)" : "afk",
	"a louca" : "alok",
	"brincadeira" : "brinks",
	"teste" : "beta",
	"copia e cola" : "c&p",
	"copiar?" : "cp",
	"como fa(s|z)" : "comofas",
	"vitória épica" : "epicwin",
	"falh(ado|ou)" : "fail",
	"perguntas frequêntes" : "faq",
	"fim de semana" : "fds",
	"fica a dica" : "fikdik",
	"pela vitoria" : "ftw",
	"pela derrota" : "ftl",
	"odiador" : "hater",
	"ri(ndo)? (alto|muito)" : "lol",
	"(iniciante|novato|virjão)" : "noob",
	"n(ã|a)o" : "n",
	"meu deus" : "mds",
	"rolando de rir" : "rofl",
	"z(o|u)ei?ro" : "troll",
	"z(o|u)ei?ra" : "trollagem",
	"z(o|u)ei?r" : "trollar",
	"z(o|u)ando" : "trollando",
	"z(o|u)ou" : "trollou",
	"você" : "vc",
	"vizualiza(ç|c)(ã|a)o" : "view",
	"vizualiza(ç|c)(õ|o)es" : "views",
	"World of Warcraft" : "wow",
	"que (merda|porra|bosta|desgraça) e essa" : "wtf",
	"tchau" : "xau",
	"cabeça" : "kbça",
	"falou" : "flw",
	"falar?" : "fl",
	"acho" : "axo",
	"é" : "eh",
	"que" : "q",
	"risos" : "rs",
	"(ha)*" : "kkk",
	"firmeza" : "fmz",
	"abraço" : "abç",
	"abraços" : "abs",
	"novidades" : "9da10",
	"até mais" : "t+",
	"demais" : "d+",
	"as vezes" : "as x",
	"cá" : "k",
	"para" : "p",
	"sim" : "s",
	"de" : "d",
	"beijo" : "bj",
	"beijo" : "bjs",
	"beijoca" : "bjok",
	"valeu" : "vlw",
	"agora" : "agr",
	"primeiro" : "1o",
	"segundo" : "2o",
	"segunda" : "2a",
	"adicionar?" : "adc",
	"quase" : "qse",
	"quando" : "qd",
	"quanto" : "qt",
	"(es)?tamos? juntos?" : "tmj",
	"muito" : "mt",
	"tam(é|e)m" : "tb",
	"depois" : "dp",
	"filh(o|a) (da|de uma) puta" : "fdp",
	"beleza" : "bl",
	"hoje" : "hj",
	"mais ou menos" : "+-",
	"mesm(o|a)" : "msm",
	"quem" : "qm",
	"comigo" : "cmg",
	"cadê" : "kd",
	"qua(l|is)quer" : "qq",
	"vocês" : "v6",
	"teclar" : "tc",
	"tá" : "tah",
	"aqui" : "aq",
	"internet" : "net",
	"só" : "soh",
	"h?e(i|y)" : "ow",
	"jogo" : "jg",
	"j(á|a)" : "jah",
	"caralho" : "krl",
	"cara" : "kra",
	"algu(é|e)m" : "alg",
	"ver?" : "v",
	"nada" : "nd",
	"aceitar?" : "acc",
	"né" : "ne",
	"pa?ra eu" : "preu",
	"ficar?" : "fik",
	"foda-?s?se" : "fdc",
	"mensagem" : "msg",
	"mensagens" : "msgs",
	"com certeza" : "cctz",
	"certeza" : "ctz",
	"verdade" : "vdd",
	"melhor amig(o|a)" : "bff",
	"babaca" : "bbc",
	"pepeca" : "ppk",
	"amigo" : "amg",
	"galera" : "glr",
	"puta q(ue)? (me )?pariu" : "pqp",
	"saudade" : "sdd",
	"saudades" : "sdds",
	"pel(o|a) ?a?mor de deus" : "pela mor",
	"boto f(é|e)" : "btf",
	"v(á|a)i? se foder?" : "vsf",
	"por favor?" : "pfv",
	"pau no cu" : "pnc",
	"por ?qu(ê|e)" : "pq",
	"tom(ou|á|ar|ei) no cu" : "tnc",
	"obrigado" : "obg",
	"timeline" : "tl",
	"retweet" : "rt",
	"(eu )?volto já" : "brb",
	"imagem" : "img",
	"pode ser" : "pdc",
	"como" : "cm",
	"pequena" : "pqna",
	"pequeno" : "pqno",
	"tudo" : "td",
	"moleque" : "mlq",
	"moleca" : "mlk",
	"mulher" : "muie",
	"homem" : "homi",
	"facebook" : "fb",
	"publicação" : "post",
	"publica" : "posta",
	"publicou" : "postou",
	"publicar" : "postar",
	"da hora" : "daora",
	"vou" : "vo",
	"tou" : "to",
	"mais" : "+",
	"menos" : "-",
}
