dicionario['geek-pt'] = {
	"pc" : "computador",
	"afk" : "longe do computador",
	"alok" : "a louca",
	"brinks" : "brincadeira",
	"beta" : "teste",
	"c&p" : "copia e cola",
	"cp" : "copia",
	"comofa(s|z)" : "como faz",
	"epicwin" : "vitória épica",
	"fail" : "falhado",
	"faq" : "perguntas frequêntes",
	"fds" : "fim de semana",
	"fi(c|k)a?di(c|k)a?" : "fica a dica",
	"ftw" : "pela vitória",
	"ftl" : "pela derrota",
	"hater" : "odiador",
	"lol" : "rindo alto",
	"noob" : "iniciante",
	"(ñ|n)" : "não",
	"naum" : "não",
	"nem" : "não",
	"nsfw" : "não é seguro para o trabalho",
	"omg" : "meu deus",
	"rofl" : "rolando de rir",
	"troll?" : "zoeiro",
	"troll?agem" : "zoeira",
	"troll?ar" : "zoar",
	"troll?ando" : "zoando",
	"troll?ou" : "zoou",
	"ce" : "você",
	"vc" : "você",
	"vs" : "você",
	"view" : "vizualização",
	"wow" : "World of Warcraft",
	"wtf" : "que merda é essa",
	"xau" : "tchau",
	"kbça" : "cabeça",
	"flw" : "falou",
	"axo" : "acho",
	"eh" : "é",
	"q" : "que",
	"k(k)*" : "risos",
	"(rs)+" : "risos",
	"fmz" : "firmeza",
	"abç" : "abraço",
	"abs" : "abraços",
	"9da10" : "novidades",
	"t+" : "até mais",
	"d+" : "demais",
	"mds" : "meu deus",
	"as x" : "as vezes",
	"k" : "cá",
	"p" : "para",
	"s" : "sim",
	"fla" : "fala",
	"d" : "de",
	"bj(o|u)?" : "beijo",
	"bjo?s" : "beijos",
	"bjok" : "beijoca",
	"vlw" : "valeu",
	"agr?" : "agora",
	"1o" : "primeiro",
	"2o" : "segundo",
	"add" : "adiciona",
	"adc" : "adiciona",
	"qse" : "quase",
	"qdo?" : "quando",
	"qndo?" : "quando",
	"qnto?" : "quanto",
	"qto" : "quanto",
	"qt" : "quantidade",
	"tmj" : "tamo junto",
	"mto?" : "muito",
	"tbm?" : "também",
	"dp" : "depois",
	"dps" : "danos por segundo",
	"fdp" : "filho da puta",
	"be?le?" : "beleza",
	"hj" : "hoje",
	"+-" : "mais ou menos",
	"msmo?" : "mesmo",
	"qm" : "quem",
	"cmg" : "comigo",
	"kd" : "cadê",
	"ql?qr?" : "qualquer",
	"v6" : "vocês",
	"tc" : "teclar",
	"tah" : "tá",
	"aki" : "aqui",
	"net" : "internet",
	"soh" : "só",
	"ow" : "ei",
	"jg" : "jogo",
	"jah" : "já",
	"krl" : "caralho",
	"kra" : "cara",
	"alg" : "alguém",
	"a v" : "a ver",
	"nd" : "nada",
	"acc" : "aceita",
	"ne" : "né",
	"preu" : "para eu",
	"fik" : "ficar",
	"fdc" : "foda-se",
	"msg" : "mensagem",
	"cctz" : "com certeza",
	"ctz" : "certeza",
	"vdd" : "verdade",
	"bff" : "melhor amigo",
	"bbc" : "babaca",
	"ppk" : "pepeca",
	"amg" : "amigo",
	"glr" : "galera",
	"pqp" : "puta que pariu",
	"sdd" : "saudade",
	"sdds" : "saudades",
	"pela mor" : "pelo amor de deus",
	"btf" : "boto fé",
	"btf(e|é)" : "boto fé",
	"vsf" : "vai se foder",
	"pfv?" : "por favor",
	"pnc" : "pau no cu",
	"pq" : "por que",
	"tnc" : "tomar no cu",
	"obg" : "obrigado",
	"tl" : "timeline",
	"rt" : "retweet",
	"brb" : "volto já",
	"idk" : "eu não sei",
	"img" : "imagem",
	"pdc" : "pode ser",
	"cm" : "como",
	"pqna" : "pequena",
	"pqno" : "pequeno",
	"td" : "tudo",
	"mlq" : "moleque",
	"mlk" : "moleca",
	"muie" : "mulher",
	"homi" : "homem",
	"fb" : "facebook",
	"post" : "publicação",
	"postei" : "publiquei",
	"postou" : "publicou",
	"postar" : "publicar",
	"daora" : "da hora",
	"vo" : "vou",
	"to" : "tou",
}
